version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn add graphql
      - run: yarn install
      - run: yarn test
      - run: npx semantic-release
