name: trunk

on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
        environment: [dom, node]
        graphql-version: [14, 15, 16]
    name: Node ${{ matrix.node }} @env ${{matrix.environment}} with grahpql@${{ matrix.graphql-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install
      - run: yarn add graphql@${{ matrix.graphql-version }}
      - run: yarn build
      - run: yarn test:${{ matrix.environment }}
        env:
          GRAPHQL_VERSION: ${{ matrix.graphql-version }}
  release:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: v16
          cache: yarn
      - run: yarn install
      - name: Make release
        id: release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          yarn -s dripip preview --json > result.json
          echo '==> Publish Result'
          jq '.' < result.json
